# Generated by Django 4.0.6 on 2022-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AerpawResource',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('modified_by', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ops_notes', models.TextField(blank=True, null=True)),
                ('resource_class', models.CharField(choices=[('allow_canonical', 'Allow Canonical'), ('exclude_canonical', 'Exclude Canonical')], default='allow_canonical', max_length=255)),
                ('resource_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('testbed', 'Testbed')], default='testbed', max_length=255)),
                ('resource_type', models.CharField(choices=[('AFRN', 'AFRN'), ('APRN', 'APRN'), ('UAV', 'UAV'), ('UGV', 'UGV'), ('3PBBE', '3PBBE'), ('other', 'Other')], default='AFRN', max_length=255)),
                ('uuid', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'AERPAW Resource',
            },
        ),
    ]
