# Generated by Django 4.0.6 on 2022-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalNumber',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('canonical_number', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_retired', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
